var userDummyData = [
        {
            "id": "RpNave-qiDUQ_EGHdL6CIA",
            "name": "Leah",
            "review_count": 105,
            "yelping_since": "2011-12-24T08:00:00.000Z",
            "useful": 129,
            "funny": 0,
            "cool": 3,
            "fans": 3,
            "average_stars": 3.9,
            "compliment_hot": 1,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 1,
            "compliment_plain": 2,
            "compliment_cool": 1,
            "compliment_funny": 1,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "gUpK1Ibyle50ZFvq6SEW9w",
            "name": "April",
            "review_count": 101,
            "yelping_since": "2008-07-02T07:00:00.000Z",
            "useful": 11,
            "funny": 3,
            "cool": 1,
            "fans": 10,
            "average_stars": 3.84,
            "compliment_hot": 2,
            "compliment_more": 0,
            "compliment_profile": 1,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 2,
            "compliment_plain": 2,
            "compliment_cool": 1,
            "compliment_funny": 1,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "hM4D0u2h9PqH2xTOPaB10A",
            "name": "William",
            "review_count": 4,
            "yelping_since": "2009-02-20T08:00:00.000Z",
            "useful": 3,
            "funny": 0,
            "cool": 0,
            "fans": 0,
            "average_stars": 4,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 0,
            "compliment_plain": 0,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "BipK9_ELmklpV7SPm3_P6g",
            "name": "Sherri",
            "review_count": 33,
            "yelping_since": "2010-05-31T07:00:00.000Z",
            "useful": 0,
            "funny": 0,
            "cool": 0,
            "fans": 1,
            "average_stars": 4.24,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 1,
            "compliment_plain": 0,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "U4INQZOPSUaj8hMjLlZ3KA",
            "name": "Michael",
            "review_count": 4063,
            "yelping_since": "2008-01-31T08:00:00.000Z",
            "useful": 410,
            "funny": 278,
            "cool": 317,
            "fans": 746,
            "average_stars": 3.87,
            "compliment_hot": 295,
            "compliment_more": 75,
            "compliment_profile": 41,
            "compliment_cute": 13,
            "compliment_list": 51,
            "compliment_note": 427,
            "compliment_plain": 648,
            "compliment_cool": 762,
            "compliment_funny": 762,
            "compliment_writer": 642,
            "compliment_photos": 561
        },
        {
            "id": "rOIrilMC7VFwFVBeQNiKMw",
            "name": "Su",
            "review_count": 54,
            "yelping_since": "2009-05-18T07:00:00.000Z",
            "useful": 2,
            "funny": 0,
            "cool": 0,
            "fans": 4,
            "average_stars": 4.22,
            "compliment_hot": 2,
            "compliment_more": 2,
            "compliment_profile": 0,
            "compliment_cute": 1,
            "compliment_list": 0,
            "compliment_note": 4,
            "compliment_plain": 3,
            "compliment_cool": 13,
            "compliment_funny": 13,
            "compliment_writer": 1,
            "compliment_photos": 1
        },
        {
            "id": "Wevzu2iYYel-q29Gctd58Q",
            "name": "Anne",
            "review_count": 1,
            "yelping_since": "2016-04-03T07:00:00.000Z",
            "useful": 0,
            "funny": 0,
            "cool": 0,
            "fans": 0,
            "average_stars": 3,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 0,
            "compliment_plain": 0,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "EAOt1UQhJD0GG3l_jv7rWA",
            "name": "Rosalyn",
            "review_count": 2,
            "yelping_since": "2017-03-31T07:00:00.000Z",
            "useful": 0,
            "funny": 0,
            "cool": 0,
            "fans": 0,
            "average_stars": 3.5,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 0,
            "compliment_plain": 0,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 0,
            "compliment_photos": 0
        },
        {
            "id": "YJquKPRim02PvqK5rEdYmQ",
            "name": "Chantelle",
            "review_count": 160,
            "yelping_since": "2014-05-10T07:00:00.000Z",
            "useful": 24,
            "funny": 0,
            "cool": 0,
            "fans": 4,
            "average_stars": 4.21,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 1,
            "compliment_plain": 4,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 1,
            "compliment_photos": 1
        },
        {
            "id": "2zX_qQUGocOdbFL-k8U0VA",
            "name": "Michael",
            "review_count": 42,
            "yelping_since": "2008-10-28T07:00:00.000Z",
            "useful": 0,
            "funny": 0,
            "cool": 0,
            "fans": 0,
            "average_stars": 4.29,
            "compliment_hot": 0,
            "compliment_more": 0,
            "compliment_profile": 0,
            "compliment_cute": 0,
            "compliment_list": 0,
            "compliment_note": 2,
            "compliment_plain": 1,
            "compliment_cool": 0,
            "compliment_funny": 0,
            "compliment_writer": 0,
            "compliment_photos": 0
        }
    ];

export default userDummyData;
