module.exports = {
  pageOne: [
      {
          "id": "FmoHNtcIw6reY7IX5eV97g",
          "name": "Cathy",
          "review_count": 499,
          "yelping_since": "2007-09-20T07:00:00.000Z",
          "useful": 763,
          "funny": 584,
          "cool": 777,
          "fans": 43,
          "average_stars": 4.24,
          "compliment_hot": 34,
          "compliment_more": 3,
          "compliment_profile": 5,
          "compliment_cute": 3,
          "compliment_list": 0,
          "compliment_note": 30,
          "compliment_plain": 54,
          "compliment_cool": 68,
          "compliment_funny": 68,
          "compliment_writer": 27,
          "compliment_photos": 11
      },
      {
          "id": "UVg9-TVTipQuyHXPkaTJuA",
          "name": "Christina",
          "review_count": 174,
          "yelping_since": "2009-03-03T08:00:00.000Z",
          "useful": 46,
          "funny": 35,
          "cool": 25,
          "fans": 9,
          "average_stars": 3.73,
          "compliment_hot": 2,
          "compliment_more": 1,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 4,
          "compliment_plain": 12,
          "compliment_cool": 4,
          "compliment_funny": 4,
          "compliment_writer": 3,
          "compliment_photos": 4
      },
      {
          "id": "E7xyQSHAndoZhq_SRAKBKQ",
          "name": "Kari",
          "review_count": 359,
          "yelping_since": "2009-05-08T07:00:00.000Z",
          "useful": 0,
          "funny": 0,
          "cool": 0,
          "fans": 8,
          "average_stars": 3.25,
          "compliment_hot": 6,
          "compliment_more": 3,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 9,
          "compliment_plain": 7,
          "compliment_cool": 5,
          "compliment_funny": 5,
          "compliment_writer": 3,
          "compliment_photos": 2
      },
      {
          "id": "dAc8XwuTkLZibyWTFAYgVw",
          "name": "Jarrod",
          "review_count": 176,
          "yelping_since": "2009-10-26T07:00:00.000Z",
          "useful": 16,
          "funny": 2,
          "cool": 2,
          "fans": 4,
          "average_stars": 3.95,
          "compliment_hot": 2,
          "compliment_more": 0,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 1,
          "compliment_plain": 2,
          "compliment_cool": 4,
          "compliment_funny": 4,
          "compliment_writer": 2,
          "compliment_photos": 2
      },
      {
          "id": "2zw5pNWAyn0vXxAylutJtg",
          "name": "Carlos",
          "review_count": 351,
          "yelping_since": "2008-12-31T08:00:00.000Z",
          "useful": 566,
          "funny": 45,
          "cool": 70,
          "fans": 4,
          "average_stars": 3.77,
          "compliment_hot": 5,
          "compliment_more": 3,
          "compliment_profile": 1,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 25,
          "compliment_plain": 61,
          "compliment_cool": 46,
          "compliment_funny": 46,
          "compliment_writer": 6,
          "compliment_photos": 4
      },
      {
          "id": "ZOXLXDo1C8nlW5a_2RpvKg",
          "name": "David",
          "review_count": 56,
          "yelping_since": "2012-01-24T08:00:00.000Z",
          "useful": 16,
          "funny": 3,
          "cool": 2,
          "fans": 0,
          "average_stars": 3.74,
          "compliment_hot": 0,
          "compliment_more": 1,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 2,
          "compliment_plain": 1,
          "compliment_cool": 1,
          "compliment_funny": 1,
          "compliment_writer": 0,
          "compliment_photos": 0
      },
      {
          "id": "knB3eczyruOuZaP3TKUKew",
          "name": "Jerry",
          "review_count": 12,
          "yelping_since": "2015-02-01T08:00:00.000Z",
          "useful": 0,
          "funny": 0,
          "cool": 0,
          "fans": 0,
          "average_stars": 4.25,
          "compliment_hot": 0,
          "compliment_more": 0,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 0,
          "compliment_plain": 0,
          "compliment_cool": 0,
          "compliment_funny": 0,
          "compliment_writer": 0,
          "compliment_photos": 0
      },
      {
          "id": "REogujfSFwb-mbjzAeHYTw",
          "name": "Beth",
          "review_count": 22,
          "yelping_since": "2008-02-29T08:00:00.000Z",
          "useful": 0,
          "funny": 0,
          "cool": 0,
          "fans": 0,
          "average_stars": 4,
          "compliment_hot": 0,
          "compliment_more": 0,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 0,
          "compliment_plain": 0,
          "compliment_cool": 0,
          "compliment_funny": 0,
          "compliment_writer": 0,
          "compliment_photos": 0
      },
      {
          "id": "quQ657_JzIKLeIYFeA-mwQ",
          "name": "Manny",
          "review_count": 138,
          "yelping_since": "2005-10-21T07:00:00.000Z",
          "useful": 7,
          "funny": 2,
          "cool": 0,
          "fans": 2,
          "average_stars": 3.7,
          "compliment_hot": 1,
          "compliment_more": 6,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 2,
          "compliment_plain": 6,
          "compliment_cool": 9,
          "compliment_funny": 9,
          "compliment_writer": 1,
          "compliment_photos": 1
      },
      {
          "id": "qJSy8cLkGGSdN9JQeG2pkg",
          "name": "dan",
          "review_count": 34,
          "yelping_since": "2009-03-31T07:00:00.000Z",
          "useful": 7,
          "funny": 2,
          "cool": 5,
          "fans": 2,
          "average_stars": 4.71,
          "compliment_hot": 0,
          "compliment_more": 0,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 2,
          "compliment_plain": 2,
          "compliment_cool": 1,
          "compliment_funny": 1,
          "compliment_writer": 1,
          "compliment_photos": 0
      }
  ],
  pageTen: [
      {
          "id": "MkyBX9POvI2wWUEAklVFYA",
          "name": "Bev",
          "review_count": 6,
          "yelping_since": "2010-12-15T08:00:00.000Z",
          "useful": 4,
          "funny": 0,
          "cool": 0,
          "fans": 0,
          "average_stars": 3.67,
          "compliment_hot": 0,
          "compliment_more": 0,
          "compliment_profile": 0,
          "compliment_cute": 0,
          "compliment_list": 0,
          "compliment_note": 0,
          "compliment_plain": 0,
          "compliment_cool": 0,
          "compliment_funny": 0,
          "compliment_writer": 0,
          "compliment_photos": 0
      }
  ]
};
