module.exports = {
  pageOne: [
      {
          "id": "-jj-I7ZilRY184XucCX_8g",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "qJSy8cLkGGSdN9JQeG2pkg",
          "stars": 5,
          "date": "2011-11-18T08:00:00.000Z",
          "text": "The Bone-in ribeye was excellent.   The apps and the wine were great, and the service was prompt and friendly.    I will recommend this as a great place to go for a steak in Vegas!",
          "useful": 1,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-Z1sBNercIPYzANVbdUo1A",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "2zw5pNWAyn0vXxAylutJtg",
          "stars": 5,
          "date": "2009-07-17T07:00:00.000Z",
          "text": "Just got back from Vegas and our second visit to Delmonico. We had the Filet Medallions($48) and they were Heavenly ! They had a carmelized onion,Mushroom mixture with a Parmesan crust that absolutely sent them into Orbit !!!!! Not to mention the Prime Dry Aged Filet that was literally \\\"Cake\\\" tender and had a deep beef flavor. We also had the Jumbo Australian Lobster tail that was sweet and cooked to perfection in a white wine reduction with aromatic veggies/herbs($95).May I also suggest the Bone In Ribeye($55) which is the house specialty....it\\'s to die for !!!!  In regards to attire it seems like a dressy place but folks were showing up with Tommy Bahama Shirts,Shorts and flip flops and were seated without question and some were \\\"dudded up\\\". My wife and I ate for about $200 but it was worth every penny !This a must stop for a special dinner if your a steak lover !!!!   Oh....our table as well as everyone else\\'s had four servers and a host !!!! Exemplary Service",
          "useful": 1,
          "funny": 0,
          "cool": 1
      },
      {
          "id": "-7O72HqM4eJF0NMCgdLjCQ",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "quQ657_JzIKLeIYFeA-mwQ",
          "stars": 5,
          "date": "2006-03-23T08:00:00.000Z",
          "text": "My client took me here after the MAGIC Show and it was phenomenal! The steak danced in my mouth. Well not really but you get the picture. The salads and sides (asparagus, potatoes) were excellent. They also have a fine wine selection. This place takes steak on another level! Highly recommended!",
          "useful": 1,
          "funny": 1,
          "cool": 0
      },
      {
          "id": "-18YJeEWx5JPyVNOlQKqyg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "dAc8XwuTkLZibyWTFAYgVw",
          "stars": 5,
          "date": "2013-05-23T07:00:00.000Z",
          "text": "My favorite steakhouse in Las Vegas, somewhere I know I can go and get a great steak and have a great atmosphere to share with friends or family.  I have been going to Delmonico since about four year ago and I have never been disappointed once.\\n\\nOne of my favorite things about this place is every time I have made a reservation I have always got seated almost exactly on time.  This place is not cheap nor is it too overpriced compared to other steakhouses in Las Vegas that don\\'t even come close to this one.\\n\\nOne of my favorite things is they have an great selection of scotches and bourbon, the have a separate menu for it and if you like either please make sure and check it out.\\n\\nGive this place a try and know that I recommend it to everyone.",
          "useful": 3,
          "funny": 0,
          "cool": 1
      },
      {
          "id": "-QMNsRIEMeT0B1zEoivd3g",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "ZOXLXDo1C8nlW5a_2RpvKg",
          "stars": 5,
          "date": "2014-01-02T08:00:00.000Z",
          "text": "This is probably one of my favorite places for steak, bread pudding, or when I wanna eat at the bar alone. Here is a summary of one of my experiences that I shared with one of my foodie friends when we ate here. \\n\\nWe ordered the Caesar Salad which was spectacularly prepared fresh able side by the maitre \\'d. It was like $30 but probably THE best salad of my life! Next was the bone in rib eye which was so perfectly seasoned and cooked! I\\'m a huge fan of sides so I got the creamed spinach, a Idaho baked potato, creamed corn, and asparagus. YES, there were amazing left overs!\\n\\nFor dessert of course it was the White Chocolate Macadamia nut Bread Pudding! If anyone knows Emril\\'s shows or books you know this is like his signature item. I have also had the Duck Egg Creme Brulee which is heavenly as well. But my go to is the bread pudding!\\n\\nThis is a place you probably wouldn\\'t wanna eat at daily, but it is a place to take special friends who enjoy good food at it\\'s best or for an awesome night of self spoiling! :)\\n\\n*Lobster bique, the butternut squash ravioli and the fried chicken are killer too!",
          "useful": 1,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-vC7STnfwQuR6DgX3CsfnQ",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "knB3eczyruOuZaP3TKUKew",
          "stars": 5,
          "date": "2015-05-30T07:00:00.000Z",
          "text": "Started off with a Chimay Blue beer and Gumbo and progressed to a perfectly cooked ribeye steak and garlic sautéed mushrooms. Very delicious.  Especially with the Oscar style asparagus a must.  Highly recommend it.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-AfWnumxLUcgx69eN1WmIQ",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "FmoHNtcIw6reY7IX5eV97g",
          "stars": 5,
          "date": "2013-02-27T08:00:00.000Z",
          "text": "I came here with some girlfriends during my Bachelorette weekend in Vegas. We had a reservation for 7 girls, and were very promptly sat at our reservation hour.\\n\\nThe service here is spectacular, and the food is equally enjoyable. My girls and I shared our entrees and side dishes, so that we could each have a taste of a little bit of everything.\\n\\nEntrees:\\n- FILET MIGNON - 9 oz, and absolutely melt-in-your-mouth yummy. This cut was like BUTTER.\\n- EMERIL\\'S BBQ SALMON - Also melted like butter with every bite. It was amazing how tender, yet well-cooked the fish was. The hash side dish that came with the meal was very complimentary!\\n- GRILLED MARINATED ORGANIC CHICKEN BREAST - Mostly juicy (a teeny bit dry), but great flavors. The fingerling potatoes were pretty standard, and the wild mushrooms weren\\'t very tasty to me.\\n- BONE IN RIBEYE - 20 oz, and great for sharing! Our waiter even cut the steak for our girls so that each could have medium rare/well.\\n- AMERICAN RED SNAPPER - the sides didn\\'t seem as appealing at first for my friend who had this dish, but she ended up enjoying them!\\n\\nSides:\\n- CREAMED CORN GRATINÉE - delicious. A great combination of that sweet and salty flavor. Texture was right on point!\\n- BUTTERED FRESH ASPARAGUS - fabulous crunch, and not so much flavor added to cover up the natural enjoyable flavor of the veggie\\n\\nAll in all, a great experience. We weren\\'t too full at the end of the meal, and didn\\'t have to worry about wasting any food or taking back any leftovers.\\n\\nHighly recommended!",
          "useful": 4,
          "funny": 1,
          "cool": 2
      },
      {
          "id": "-cHz-QqaPDMvKKtMPDXNQA",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "REogujfSFwb-mbjzAeHYTw",
          "stars": 5,
          "date": "2016-06-29T07:00:00.000Z",
          "text": "The steak melts in your mouth. This restaurant is superb. The food is wonderful. The service is fantastic. You should make a reservation.",
          "useful": 1,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-8t63nMvQKH-Bj1OSQx54Q",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "UVg9-TVTipQuyHXPkaTJuA",
          "stars": 5,
          "date": "2010-07-21T07:00:00.000Z",
          "text": "Man.. I\\'m drooling just thinking about the wonderful birthday meal I had here (courtesy of dearest Hubby).\\n\\nI loved how the theme of the restaurant was very New Orleans/Cajun inspired.\\n\\nBefore we even ordered, we got to try these ox tail thingies, compliments of the chef. Pretty good.\\n\\nWe started with the BBQ shrimp. Delish.\\n\\nI had the filet, and Hubby had the bone-in filet. According to him, it was extremely good, and he liked it better than the bone-in at Fleming\\'s. I absolutely loved my filet. It had a cajun spice flavor, and it was so good that I didn\\'t even want to dip it in Emeril\\'s version of A1 sauce (yeah.. it\\'s an Emeril restaurant.. didn\\'t know that till I looked at the menu, and I admit initially I was a little turned off by that).\\n\\nWe shared asparagus and mushrooms as sides, and their mushrooms were superb. They didn\\'t use the button mushrooms that most steakhouses use. Instead, I think they were shiitake mushrooms, or some sort of mushrooms that tasted similar/looked similar to shiitake mushrooms. Either way, very good.\\n\\nWe ended the meal with a complimentary sorbet that was yum, and we also ordered their dessert of the night, which was a blackberry cheesecake that was yum as well.\\n\\nLastly, according to Hubby, they had a great wine selection.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-zjupoKtXaPmpyn5WiSxeg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "abzDYj8JKz8-YQslYuzBuQ",
          "stars": 5,
          "date": "2015-11-29T08:00:00.000Z",
          "text": "We couldn\\'t help but take a photo with our favorite server, Michael Jackson. We are fortunate to have experienced Michael Jackson\\'s tailored hospitality, authentic personality, and genuine interest in our dining. Of course the food is excellent, but we come here because our service is impeccable.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      }
  ],
  pageTen: [
      {
          "id": "2dEEIG900VokryMXxiR6uw",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "evBTA7-8xRDo8j7CgoThCw",
          "stars": 4,
          "date": "2016-02-29T08:00:00.000Z",
          "text": "We had drinks in the bar followed by dinner. The drinks were fine but the bar atmosphere is stark. The chairs are not comfortable and it just isn\\'t very inviting. Our meal was excellent! We had bone-in NY and bone-in ribeye. The truffle potato chips are a must. Our wait staff was very good too..professional and helpful. Again, not impressed with the atmosphere. It has a big dining hall feel. Emeril often makes gluten free modifications but there aren\\'t any here.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "2Ebi2fyQYAC1Evn8JZg2DA",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "wczP8ehoY_SWCRRLFuSNrg",
          "stars": 4,
          "date": "2014-11-26T08:00:00.000Z",
          "text": "After three years of waiting, I finally found myself back to Delmonico Steakhouse. Why did I come here out of all the other excellent steak houses on the Las Vegas strip?\\n\\n1 reason: Truffle Parmesan potato chips. they are like crack, you simply can\\'t stop eating them :)\\n\\nI ordered the Certified Piedmontese steak, NY Strip steak ($60), grilled in olive oil, sea salt, roasted garlic and rosemary. At 16 ounces, each tender bite was worth every dollar.\\n\\nGirlfriend ordered the grilled cheese sandwich with tomato soup and said it was very good.\\n\\nService is impeccable with a three person staff dedicated to your table and they make your experience worth the high price tag that is at Delmoncio!",
          "useful": 2,
          "funny": 2,
          "cool": 3
      },
      {
          "id": "2FnSdsWO0q3aAe45-rIkGg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "BipK9_ELmklpV7SPm3_P6g",
          "stars": 4,
          "date": "2017-03-06T08:00:00.000Z",
          "text": "I had the seared halibut with peas. It was very good and not dry.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "2gnMmhBMRqaYt6iSNny5bg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "r2yT9tP_jpYROAnfzBbFLA",
          "stars": 4,
          "date": "2015-12-03T08:00:00.000Z",
          "text": "Very proper waiting on you, we were one of the first to arrive. \\n\\nFood was excellent, most steak houses of this caliber are--if you\\'re looking for a typical wine and dine situation this is the place. \\n\\nAmbiance was nice but nothing memorable.",
          "useful": 9,
          "funny": 7,
          "cool": 11
      },
      {
          "id": "2gRUqhWj3kd__vCZ5pp_ZA",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "XwYcTqPIZgHwAPO70M6Ruw",
          "stars": 4,
          "date": "2011-11-01T07:00:00.000Z",
          "text": "We decided to pay Delmonico another visit after how successful our first experience was.  This time we only had a party of 4 (last time we had a party of at least 20).  The service of course was still great.\\n\\nWe started with the tuna/salmon tar tare - wasn\\'t mediocre but still good\\n\\nThe men ordered the bone-in rib eyes and the ladies ordered the petite rib eye special - that came with a marrow/wine sauce over the steaks in place of butter.  My husband and I both ordered ours medium-rare, the other pair ordered theirs medium.  When we received our steaks, they ended up giving everyone the wrong steaks.  The other couple seemed to have enjoyed our medium-rare steaks though!\\n\\nWe ended our dinner sharing 2 desserts, the banana creme pie and creme brulee - both were yummy.\\n\\nOutside of our mixed up orders, we will definitely be back.  Their steaks melt like butta!",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "-j3RhQOGGW-uav1kNKptnQ",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "XduciX-f9ONDZ-rUhs3PfQ",
          "stars": 4,
          "date": "2013-03-31T07:00:00.000Z",
          "text": "Everything we had was amazing here. \\nGreat service, great atmosphere and best of all... great food.\\nTruffle Potato Chips... highly recommend.  When I first saw it... was a little skeptical. But.. they are amazing.\\nVine rippen tomato salad, really good.  cheese was super fresh and the tomatos were very sweet and rip.  \\nRib Eye - was perfectly cook, medium rare.  perfect crust and was just so good.  \\nI can see why my friends made it a tradition to come here.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "4rFufu6h3QRkHoNNEH2GZg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "T10OVryXjBITJ1w_7_hsSw",
          "stars": 4,
          "date": "2009-09-24T07:00:00.000Z",
          "text": "Came here for my 21st birthday with my family. Was almost the best steak I had in my life. We also had some good wine.\\n\\nCame back here for a 2nd time recently with my sister before we headed off to a concert, and it wasn\\'t as good this time. Not sure what it was. Portions are large, and prices still relatively expensive, but it just didn\\'t sweep me off my feet like the first time.\\n\\nBut it still gets 4 stars. Folded napkins each time you leave your seat. All good.\\n\\nAnd my sis will prob remember me eating the leftovers in the hotel room after the convert. Ahahaha.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "3L3XegrPaSDMX3STBq8VSQ",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "hO8d0zwNjUI3K3eQullpTQ",
          "stars": 4,
          "date": "2012-07-16T07:00:00.000Z",
          "text": "The bone in rib eye was delicous and the cream of spinach and the grits and bacon sides were flavorful.  This is a huge slab of meat and I had a hard time finishing all 18 ounces of it.  The only reason why I didn\\'t give this place a 5 was because of house expensive it is.  I\\'m all about quality at an affordable price and I would only go again to this place for like a 10 year anniversary.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "2tji6m94yh8mG7MCP05gvg",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "iEcLqPSXmFY5Csm49v_9lA",
          "stars": 4,
          "date": "2014-07-17T07:00:00.000Z",
          "text": "Our party of six dined at Delmonico for my 50th birthday celebration.   In short, the service was outstanding!  Our head waiter was Michael and the manager on the floor was Vincent.   We also had at least two others who served us.  All were very professional and patient. Our party was not the eaisiest to serve that night, but what happens in Vegas...!\\n\\nObviously food tastes are very subjective.  My bone in ribeye and twice baked potato were great.  I did not care too much for the chicken and waffle dish my wife had... neither did she.  The shrimp appetizer was a 10, as was the crab dish.   The desserts... Creme Brulee, banana creme pie and chocolate cake were very good also.  Overall, a very nice experience.  We will return.",
          "useful": 0,
          "funny": 0,
          "cool": 0
      },
      {
          "id": "2vt7WljElh2iifOD7B4H9A",
          "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
          "user_id": "EbUHqkncLUhl0a8GC8te6Q",
          "stars": 4,
          "date": "2009-06-04T07:00:00.000Z",
          "text": "Awesome Steaks! I have never seen a piece of prime rib so big! Nothing jumped out  at  me as exceptional but over all it was very tasty. Waiter was very knowedgable about the wine list which was a plus!",
          "useful": 0,
          "funny": 0,
          "cool": 0
      }
  ]
};


//
// {
//     "reviews": [
//         {
//             "id": "2dEEIG900VokryMXxiR6uw",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "evBTA7-8xRDo8j7CgoThCw",
//             "stars": 4,
//             "date": "2016-02-29T08:00:00.000Z",
//             "text": "We had drinks in the bar followed by dinner. The drinks were fine but the bar atmosphere is stark. The chairs are not comfortable and it just isn\\'t very inviting. Our meal was excellent! We had bone-in NY and bone-in ribeye. The truffle potato chips are a must. Our wait staff was very good too..professional and helpful. Again, not impressed with the atmosphere. It has a big dining hall feel. Emeril often makes gluten free modifications but there aren\\'t any here.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "2Ebi2fyQYAC1Evn8JZg2DA",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "wczP8ehoY_SWCRRLFuSNrg",
//             "stars": 4,
//             "date": "2014-11-26T08:00:00.000Z",
//             "text": "After three years of waiting, I finally found myself back to Delmonico Steakhouse. Why did I come here out of all the other excellent steak houses on the Las Vegas strip?\\n\\n1 reason: Truffle Parmesan potato chips. they are like crack, you simply can\\'t stop eating them :)\\n\\nI ordered the Certified Piedmontese steak, NY Strip steak ($60), grilled in olive oil, sea salt, roasted garlic and rosemary. At 16 ounces, each tender bite was worth every dollar.\\n\\nGirlfriend ordered the grilled cheese sandwich with tomato soup and said it was very good.\\n\\nService is impeccable with a three person staff dedicated to your table and they make your experience worth the high price tag that is at Delmoncio!",
//             "useful": 2,
//             "funny": 2,
//             "cool": 3
//         },
//         {
//             "id": "2FnSdsWO0q3aAe45-rIkGg",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "BipK9_ELmklpV7SPm3_P6g",
//             "stars": 4,
//             "date": "2017-03-06T08:00:00.000Z",
//             "text": "I had the seared halibut with peas. It was very good and not dry.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "2gnMmhBMRqaYt6iSNny5bg",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "r2yT9tP_jpYROAnfzBbFLA",
//             "stars": 4,
//             "date": "2015-12-03T08:00:00.000Z",
//             "text": "Very proper waiting on you, we were one of the first to arrive. \\n\\nFood was excellent, most steak houses of this caliber are--if you\\'re looking for a typical wine and dine situation this is the place. \\n\\nAmbiance was nice but nothing memorable.",
//             "useful": 9,
//             "funny": 7,
//             "cool": 11
//         },
//         {
//             "id": "2gRUqhWj3kd__vCZ5pp_ZA",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "XwYcTqPIZgHwAPO70M6Ruw",
//             "stars": 4,
//             "date": "2011-11-01T07:00:00.000Z",
//             "text": "We decided to pay Delmonico another visit after how successful our first experience was.  This time we only had a party of 4 (last time we had a party of at least 20).  The service of course was still great.\\n\\nWe started with the tuna/salmon tar tare - wasn\\'t mediocre but still good\\n\\nThe men ordered the bone-in rib eyes and the ladies ordered the petite rib eye special - that came with a marrow/wine sauce over the steaks in place of butter.  My husband and I both ordered ours medium-rare, the other pair ordered theirs medium.  When we received our steaks, they ended up giving everyone the wrong steaks.  The other couple seemed to have enjoyed our medium-rare steaks though!\\n\\nWe ended our dinner sharing 2 desserts, the banana creme pie and creme brulee - both were yummy.\\n\\nOutside of our mixed up orders, we will definitely be back.  Their steaks melt like butta!",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "-j3RhQOGGW-uav1kNKptnQ",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "XduciX-f9ONDZ-rUhs3PfQ",
//             "stars": 4,
//             "date": "2013-03-31T07:00:00.000Z",
//             "text": "Everything we had was amazing here. \\nGreat service, great atmosphere and best of all... great food.\\nTruffle Potato Chips... highly recommend.  When I first saw it... was a little skeptical. But.. they are amazing.\\nVine rippen tomato salad, really good.  cheese was super fresh and the tomatos were very sweet and rip.  \\nRib Eye - was perfectly cook, medium rare.  perfect crust and was just so good.  \\nI can see why my friends made it a tradition to come here.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "4rFufu6h3QRkHoNNEH2GZg",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "T10OVryXjBITJ1w_7_hsSw",
//             "stars": 4,
//             "date": "2009-09-24T07:00:00.000Z",
//             "text": "Came here for my 21st birthday with my family. Was almost the best steak I had in my life. We also had some good wine.\\n\\nCame back here for a 2nd time recently with my sister before we headed off to a concert, and it wasn\\'t as good this time. Not sure what it was. Portions are large, and prices still relatively expensive, but it just didn\\'t sweep me off my feet like the first time.\\n\\nBut it still gets 4 stars. Folded napkins each time you leave your seat. All good.\\n\\nAnd my sis will prob remember me eating the leftovers in the hotel room after the convert. Ahahaha.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "3L3XegrPaSDMX3STBq8VSQ",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "hO8d0zwNjUI3K3eQullpTQ",
//             "stars": 4,
//             "date": "2012-07-16T07:00:00.000Z",
//             "text": "The bone in rib eye was delicous and the cream of spinach and the grits and bacon sides were flavorful.  This is a huge slab of meat and I had a hard time finishing all 18 ounces of it.  The only reason why I didn\\'t give this place a 5 was because of house expensive it is.  I\\'m all about quality at an affordable price and I would only go again to this place for like a 10 year anniversary.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "2tji6m94yh8mG7MCP05gvg",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "iEcLqPSXmFY5Csm49v_9lA",
//             "stars": 4,
//             "date": "2014-07-17T07:00:00.000Z",
//             "text": "Our party of six dined at Delmonico for my 50th birthday celebration.   In short, the service was outstanding!  Our head waiter was Michael and the manager on the floor was Vincent.   We also had at least two others who served us.  All were very professional and patient. Our party was not the eaisiest to serve that night, but what happens in Vegas...!\\n\\nObviously food tastes are very subjective.  My bone in ribeye and twice baked potato were great.  I did not care too much for the chicken and waffle dish my wife had... neither did she.  The shrimp appetizer was a 10, as was the crab dish.   The desserts... Creme Brulee, banana creme pie and chocolate cake were very good also.  Overall, a very nice experience.  We will return.",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         },
//         {
//             "id": "2vt7WljElh2iifOD7B4H9A",
//             "business_id": "--9e1ONYQuAa-CB_Rrw7Tw",
//             "user_id": "EbUHqkncLUhl0a8GC8te6Q",
//             "stars": 4,
//             "date": "2009-06-04T07:00:00.000Z",
//             "text": "Awesome Steaks! I have never seen a piece of prime rib so big! Nothing jumped out  at  me as exceptional but over all it was very tasty. Waiter was very knowedgable about the wine list which was a plus!",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0
//         }
//     ],
//     "users": [
//         {
//             "id": "evBTA7-8xRDo8j7CgoThCw",
//             "name": "David",
//             "review_count": 12,
//             "yelping_since": "2012-01-28T08:00:00.000Z",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0,
//             "fans": 0,
//             "average_stars": 2.92,
//             "compliment_hot": 0,
//             "compliment_more": 0,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 0,
//             "compliment_plain": 0,
//             "compliment_cool": 0,
//             "compliment_funny": 0,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "XwYcTqPIZgHwAPO70M6Ruw",
//             "name": "Na",
//             "review_count": 22,
//             "yelping_since": "2009-12-19T08:00:00.000Z",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0,
//             "fans": 0,
//             "average_stars": 3.5,
//             "compliment_hot": 0,
//             "compliment_more": 0,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 0,
//             "compliment_plain": 0,
//             "compliment_cool": 1,
//             "compliment_funny": 1,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "T10OVryXjBITJ1w_7_hsSw",
//             "name": "Anita",
//             "review_count": 370,
//             "yelping_since": "2008-12-22T08:00:00.000Z",
//             "useful": 192,
//             "funny": 119,
//             "cool": 78,
//             "fans": 24,
//             "average_stars": 3.86,
//             "compliment_hot": 25,
//             "compliment_more": 1,
//             "compliment_profile": 3,
//             "compliment_cute": 2,
//             "compliment_list": 2,
//             "compliment_note": 6,
//             "compliment_plain": 24,
//             "compliment_cool": 32,
//             "compliment_funny": 32,
//             "compliment_writer": 8,
//             "compliment_photos": 15
//         },
//         {
//             "id": "hO8d0zwNjUI3K3eQullpTQ",
//             "name": "Leo",
//             "review_count": 69,
//             "yelping_since": "2012-06-28T07:00:00.000Z",
//             "useful": 2,
//             "funny": 0,
//             "cool": 0,
//             "fans": 2,
//             "average_stars": 3.99,
//             "compliment_hot": 0,
//             "compliment_more": 0,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 1,
//             "compliment_plain": 1,
//             "compliment_cool": 0,
//             "compliment_funny": 0,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "iEcLqPSXmFY5Csm49v_9lA",
//             "name": "Kevin",
//             "review_count": 13,
//             "yelping_since": "2009-08-09T07:00:00.000Z",
//             "useful": 4,
//             "funny": 1,
//             "cool": 0,
//             "fans": 0,
//             "average_stars": 3.23,
//             "compliment_hot": 0,
//             "compliment_more": 0,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 0,
//             "compliment_plain": 0,
//             "compliment_cool": 0,
//             "compliment_funny": 0,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "XduciX-f9ONDZ-rUhs3PfQ",
//             "name": "Sam",
//             "review_count": 476,
//             "yelping_since": "2007-08-29T07:00:00.000Z",
//             "useful": 41,
//             "funny": 20,
//             "cool": 18,
//             "fans": 5,
//             "average_stars": 3.6,
//             "compliment_hot": 4,
//             "compliment_more": 2,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 2,
//             "compliment_plain": 3,
//             "compliment_cool": 7,
//             "compliment_funny": 7,
//             "compliment_writer": 1,
//             "compliment_photos": 0
//         },
//         {
//             "id": "BipK9_ELmklpV7SPm3_P6g",
//             "name": "Sherri",
//             "review_count": 33,
//             "yelping_since": "2010-05-31T07:00:00.000Z",
//             "useful": 0,
//             "funny": 0,
//             "cool": 0,
//             "fans": 1,
//             "average_stars": 4.24,
//             "compliment_hot": 0,
//             "compliment_more": 0,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 1,
//             "compliment_plain": 0,
//             "compliment_cool": 0,
//             "compliment_funny": 0,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "EbUHqkncLUhl0a8GC8te6Q",
//             "name": "Autumn",
//             "review_count": 36,
//             "yelping_since": "2009-02-19T08:00:00.000Z",
//             "useful": 2,
//             "funny": 0,
//             "cool": 0,
//             "fans": 0,
//             "average_stars": 4.21,
//             "compliment_hot": 0,
//             "compliment_more": 1,
//             "compliment_profile": 0,
//             "compliment_cute": 0,
//             "compliment_list": 0,
//             "compliment_note": 0,
//             "compliment_plain": 2,
//             "compliment_cool": 0,
//             "compliment_funny": 0,
//             "compliment_writer": 0,
//             "compliment_photos": 0
//         },
//         {
//             "id": "r2yT9tP_jpYROAnfzBbFLA",
//             "name": "Rachel",
//             "review_count": 213,
//             "yelping_since": "2010-05-03T07:00:00.000Z",
//             "useful": 1262,
//             "funny": 517,
//             "cool": 510,
//             "fans": 77,
//             "average_stars": 3.7,
//             "compliment_hot": 93,
//             "compliment_more": 9,
//             "compliment_profile": 6,
//             "compliment_cute": 14,
//             "compliment_list": 2,
//             "compliment_note": 73,
//             "compliment_plain": 159,
//             "compliment_cool": 141,
//             "compliment_funny": 141,
//             "compliment_writer": 52,
//             "compliment_photos": 42
//         },
//         {
//             "id": "wczP8ehoY_SWCRRLFuSNrg",
//             "name": "Philip",
//             "review_count": 747,
//             "yelping_since": "2011-05-13T07:00:00.000Z",
//             "useful": 282,
//             "funny": 306,
//             "cool": 182,
//             "fans": 69,
//             "average_stars": 3.34,
//             "compliment_hot": 45,
//             "compliment_more": 7,
//             "compliment_profile": 10,
//             "compliment_cute": 1,
//             "compliment_list": 2,
//             "compliment_note": 48,
//             "compliment_plain": 71,
//             "compliment_cool": 83,
//             "compliment_funny": 83,
//             "compliment_writer": 30,
//             "compliment_photos": 35
//         }
//     ]
// }
